unittests_task:
  container:
    image: debian:bullseye
    cpu: 1
    memory: 1G
  before_install_script:
    - apt-get -qq update
    - apt-get install -yq git python3 python3-pip python3-setuptools python3-venv
    - apt-get install -yq libsnappy-dev zlib1g-dev libbz2-dev libgflags-dev liblz4-dev librocksdb-dev libleveldb-dev libboost-all-dev libsodium-dev
  version_script:
    - python3 --version
  tag_script:
    - git tag
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $(python3 --version) && cat requirements.txt
    populate_script: mkdir -p ~/.cache/pip
  install_script:
    # test framework -related deps
    - pip install pycodestyle
    - pip install pytest-asyncio
    - pip install pytest-cov
    - pip install coveralls
    - pip install Sphinx
    # e-x itself
    - pip install 'Cython<3.0'  # for rocksdb
    - pip install ".[rocksdb]"
    # hashes and other altcoin-specific stuff
    - pip install tribushashm
    - pip install blake256
    - pip install dash_hash
    - pip install git+https://github.com/bitcoinplusorg/x13-hash
    - pip install xevan_hash
    - pip install quark_hash
    - pip install groestlcoin_hash
    - pip install x16r_hash
    - pip install pycryptodomex
    - pip install git+https://github.com/Electra-project/nist5_hash
    - pip install git+https://github.com/RitoProject/x21s_hash
    - pip install x16rv2_hash
    - pip install git+https://github.com/VerusCoin/verushashpy
    - pip install bell-yespower
    - pip install cpupower
    - pip install bitweb_yespower==1.0.5
  script:
    - pytest --cov=electrumx
  coveralls_script:
    - if [ ! -z "$COVERALLS_REPO_TOKEN" ] ; then coveralls ; fi
  env:
    # following CI_* env vars are set up for coveralls
    CI_NAME: "CirrusCI"
    CI_BUILD_NUMBER: $CIRRUS_BUILD_ID
    CI_JOB_ID: $CIRRUS_TASK_ID
    CI_BUILD_URL: "https://cirrus-ci.com/task/$CIRRUS_TASK_ID"
    CI_BRANCH: $CIRRUS_BRANCH
    CI_PULL_REQUEST: $CIRRUS_PR
    # in addition, COVERALLS_REPO_TOKEN is set as an "override" in https://cirrus-ci.com/settings/...

pycodestyle_task:
  container:
    image: python:3.8
    cpu: 1
    memory: 1G
  install_script:
    - pip install pycodestyle
  script:
    - pycodestyle --max-line-length=100 electrumx/server/*.py electrumx/lib/*.py *.py

build_docs_task:
  # note: this build task is not related to read-the-docs; it is only here to sanity-check the docs can be built.
  #       For the read-the-docs build, see .readthedocs.yml
  #       and the webhook set up in https://github.com/spesmilo/electrumx/settings/hooks
  container:
    image: python:3.11
    cpu: 1
    memory: 1G
  install_script:
    - pip install -r docs/requirements-docs.txt
  env:
    LC_ALL: "C"
  script:
    - sh -c "cd docs && make html"
