#!/usr/bin/env python3
# -*- coding: utf-8 ; mode: python -*-
import os
import sys


if __name__ == '__main__':
    src_dir = os.path.join(os.path.dirname(__file__), "src")
    sys.path.insert(0, src_dir)
    from electrumx.cli.electrumx_rpc import main
    sys.exit(main())
